spring:
  application:
    name: library
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/library
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 5s
        heartbeat:
          enabled: true
          ttl: 10s

management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8081
  servlet:
    context-path: /library
file:
  upload:
    item: /uploads/image/item


