spring:
  profiles:
    active: dev
  application:
    name: library
  cloud:
    consul:
      config:
        format: YAML
        data-key: application
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 5s
        heartbeat:
          enabled: true
          ttl: 10s
  config:
    import: optional:consul:localhost:8500